[theme]
primaryColor = '#E694FF'
backgroundColor = '#00172B'
secondaryBackgroundColor = '#0083B8'
textColor = '#FFFFFF'
font = "sans serif"

[browser]
gatherUsageStats = false


[server]
maxMessageSize = 1000